In [1]:
!pip install yfinance pandas numpy matplotlib scikit-learn

Requirement already satisfied: yfinance in /opt/anaconda3/lib/python3.13/site-packages (1.3.0)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (2.3.5)
Requirement already satisfied: matplotlib in /opt/anaconda3/lib/python3.13/site-packages (3.10.6)
Requirement already satisfied: scikit-learn in /opt/anaconda3/lib/python3.13/site-packages (1.7.2)
Requirement already satisfied: requests>=2.31 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.32.5)
Requirement already satisfied: multitasking>=0.0.7 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.5.0)
Requirement already satisfied: pytz>=2022.5 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.0.5)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.15 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (5.29.3)
Requirement already satisfied: websockets>=13.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: scipy>=1.8.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: soupsieve>1.2 in /opt/anaconda3/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /opt/anaconda3/lib/python3.13/site-packages (from curl_cffi>=0.15->yfinance) (2025.11.12)
Requirement already satisfied: rich in /opt/anaconda3/lib/python3.13/site-packages (from curl_cffi>=0.15->yfinance) (14.2.0)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.13/site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (2.23)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from rich->curl_cffi>=0.15->yfinance) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.13/site-packages (from rich->curl_cffi>=0.15->yfinance) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)

In [2]:
# importing librabries

import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt

In [6]:
# Download 5 years of price data for 5 stocks using yfinance

stocks = ["AAPL","MSFT","NVDA","GOOGL","AMZN"]
prices = yf.download(
    stocks,
    start = "2021-05-26",
    auto_adjust = True,
    progress = False
)["Open"] # type of price(Open,High,Low,Close,Volume)

prices.head()

Ticker            AAPL        AMZN       GOOGL        MSFT       NVDA
Date
2021-05-26  123.228127  162.925507  117.353089  240.643945  15.547065
2021-05-27  121.921965  161.501999  116.847259  239.204399  15.421133
2021-05-28  121.405362  160.985001  116.678145  239.501937  15.462029
2021-06-01  120.810762  160.453003  116.749070  237.006701  15.863266
2021-06-02  120.917972  160.399994  116.653849  235.931799  16.194682

In [8]:
# Calculate daily returns
returns = prices.pct_change().dropna() # calculates return (pt - pt-1)/pt-1
returns.head()

Ticker          AAPL      AMZN     GOOGL      MSFT      NVDA
Date
2021-05-27 -0.010600 -0.008737 -0.004310 -0.005982 -0.008100
2021-05-28 -0.004237 -0.003201 -0.001447  0.001244  0.002652
2021-06-01 -0.004898 -0.003305  0.000608 -0.010418  0.025950
2021-06-02  0.000887 -0.000330 -0.000816 -0.004535  0.020892
2021-06-03 -0.007416 -0.007472 -0.009709 -0.011552  0.021404

In [10]:
# create portfolio weights
weights = np.array([0.3, 0.2, 0.1, 0.2, 0.2])

portfolio_returns = returns.dot(weights) # dot product of returns and weights

# display first few portfolio returns
print(portfolio_returns.head())

Date
2021-05-27   -0.008175
2021-05-28   -0.001277
2021-06-01    0.001037
2021-06-02    0.003390
2021-06-03   -0.002720
dtype: float64

In [15]:
# Sort historical portfolio returns to find the VaR percentile
sorted_returns = portfolio_returns.sort_values()# 
print(sorted_returns)

# 5th percentile (95% VaR)
historical_var = np.percentile(portfolio_returns, 5)

print(historical_var)

Date
2024-08-05   -0.077318
2022-01-24   -0.061453
2025-04-04   -0.060437
2025-04-03   -0.054648
2022-09-13   -0.053734
                ...
2022-10-04    0.052952
2023-05-25    0.053127
2023-02-02    0.058567
2022-05-27    0.061742
2022-02-25    0.075550
Length: 1254, dtype: float64
-0.025621003415124334

In [16]:
# Calculate CVaR as the average of returns below the VaR threshold

tail_losses = portfolio_returns[portfolio_returns <= historical_var]

historical_cvar = tail_losses.mean()

print(historical_cvar)

-0.03599370640257526

In [17]:
print(tail_losses.head())
print(len(tail_losses))

Date
2021-09-20   -0.038102
2021-12-14   -0.026802
2022-01-05   -0.026069
2022-01-10   -0.027929
2022-01-13   -0.027161
dtype: float64
63

In [18]:
# Compare historical vs parametric VaR 

mean_return = portfolio_returns.mean()
std_return = portfolio_returns.std()

print(mean_return)
print(std_return)

0.0011090996693750084
0.01585609607039292

In [19]:
parametric_var = mean_return - (1.645 * std_return)

print(parametric_var)

-0.024974178366421344

In [20]:
print("Historical VaR:", historical_var)
print("Parametric VaR:", parametric_var)

Historical VaR: -0.025621003415124334
Parametric VaR: -0.024974178366421344